version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ../../scripts/redis:/docker-entrypoint-initdb.d
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis_data:
