version: '3.8'

services:
  app:
    build: .
    container_name: wechat-book-reader-backend
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - wechat_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wechat_network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - wechat_network

networks:
  wechat_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
